# Run with
# docker build -f ./Docker/DOCKERFILE -t data-anomaly-detector:latest .

# 21/March/2026
# JRE 25 Patch 2
# Minimal image for smaller size
FROM eclipse-temurin:25.0.2_10-jre-ubi10-minimal@sha256:cf56857a708b374ecce43fac9d6049af0883fe50c829d81928381423dbe4b680

COPY ./build/libs/Data-Anomaly-Detector-0.0.1-SNAPSHOT.jar /usr/local/bin/Data-Anomaly-Detector.jar

RUN chmod +x /usr/local/bin/Data-Anomaly-Detector.jar

EXPOSE 8080

CMD ["java", "-jar", "/usr/local/bin/Data-Anomaly-Detector.jar", "$@"]