
# Run with
# docker-compose -p data-anomaly-detector-all -f .\Docker\docker-compose-with-rabbitmq.yml up -d

networks:
  data-anomaly:

services:
  rabbitmq:
    networks:
      - data-anomaly
    # RabbitMQ
    # https://hub.docker.com/layers/library/rabbitmq/4.2.5-management-alpine/images/sha256-236bb5ddf99476e9856e3ecc157c81bc8666379c4bc85253af42996f0bae74e3
    image: rabbitmq:4.2.5-management-alpine@sha256:7983ce30209cb12a4423907cfafe9eebcfa3dfc8e7463a444b1070bf0f52851c
    restart: always
    ports:
      # outside:inside
      - 5672:5672 # For app connection via AMQP
      - 15672:15672 # For access to the management UI
    environment:
      # username and pass default to guest/guest
      username: "guest"
      password: "guest"


  data-anomaly-detector:
    networks:
      - data-anomaly
    image: data-anomaly-detector:latest
    restart: always
    # expose the ports to connect from outside docker env
    ports:
      # outside:inside
      - 3000:8080
    environment:
      INBOUND_QUEUE: "inbound"
      DATASET-SIZE: 100
      ANOMALY-THRESHOLD: 3
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      RABBITMQ_PORT: 5672
      RABBITMQ_HOST: rabbitmq
      # JAVA_TOOL_OPTIONS: ''


