# Run with
# docker-compose -p data-anomaly-detector-full -f .\Docker\docker-compose-full-scenario.yaml up -d

networks:
  data-anomaly:

services:
  rabbitmq:
    networks:
      - data-anomaly
    container_name: rabbitmq
    # RabbitMQ
    # https://hub.docker.com/layers/library/rabbitmq/4.2.5-management-alpine/images/sha256-236bb5ddf99476e9856e3ecc157c81bc8666379c4bc85253af42996f0bae74e3
    image: rabbitmq:4.2.5-management-alpine@sha256:7983ce30209cb12a4423907cfafe9eebcfa3dfc8e7463a444b1070bf0f52851c
    restart: always
    ports:
      # outside:inside
      - 5672:5672 # For app connection via AMQP
      - 15672:15672 # For access to the management UI
    environment:
      # username and pass default to guest/guest
      username: "guest"
      password: "guest"


  data-anomaly-detector:
    networks:
      - data-anomaly
    image: data-anomaly-detector:latest
    container_name: anomaly-detector
    restart: always
    depends_on:
      - rabbitmq
    # expose the ports to connect from outside docker env
    ports:
      # outside:inside
      - 3000:8080
    environment:
      INBOUND_QUEUE: "inbound"
      DATASET-SIZE: 100
      ANOMALY-THRESHOLD: 3
      RABBITMQ_USER: "guest"
      RABBITMQ_PASS: "guest"
      RABBITMQ_PORT: 5672
      RABBITMQ_HOST: rabbitmq
      
  data-producer:
    networks:
      - data-anomaly
    image: data-producer-mock:latest
    container_name: data-producer
    depends_on:
      - rabbitmq
    # add args directly to command like here
    # args are:
    # --anomalyOdds ANOMALY_ODDS
    # --targetQueue TARGET_QUEUE
    # --messageDelay MESSAGE_DELAY
    # --RabbitHost RABBITMQ_HOST
    # --RabbitPort RABBITMQ_PORT
    # --RabbitUsername RABBITMQ_USER
    # --RabbitPassword RABBITMQ_PASS
    command: "--RabbitHost rabbitmq"
    
  # Dozzle (https://dozzle.dev/) added to facilitate log monitoring of apps without needing Docker desktop
  # Especially to allow easier monitoring of both Producer and Consumer apps
  dozzle:
    networks:
      - data-anomaly
    image: amir20/dozzle:v10.0.5
    container_name: dozzle
    restart: always
    ports:
      - 7010:8080
    # make sure volume is readonly
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
        

