global:
  # how often to scrape targets
  scrape_interval:     15s
  # how often will evaluate rules
  evaluation_interval: 5s

# rules are used for generating new time series and/or alerts
rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  # prometheus monitor itself
  - job_name: prometheus
    metrics_path: "/metrics" # default for metrics_path
    static_configs:
      - targets: ['localhost:9090']
  # prometheus monitors grafana
  - job_name: grafana
    metrics_path: "/metrics" # default for metrics_path
    static_configs:
      - targets: ['grafana:3000']
  # monitor the anomaly-detector app
  - job_name: "anomaly-detector"
    metrics_path: "/actuator/prometheus"
    static_configs:
    # This should be aligned with the file docker-compose-with-telemetry.yaml
    - targets: ["anomaly-detector:8080"]

