name: PR Build Pipeline

on:
  workflow_dispatch:

  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Data-Anomaly-Detector
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4
        with:
          path: ./Data-Anomaly-Detector

      - id: setup_java
        name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 25
          overwrite-settings: false

      - id: gradlew_permissions
        name: Gradlew Permissions
        shell: bash
        run: |
          chmod +x gradlew

      - id: gradlew_clean
        name: Gradle Clean
        shell: bash
        run: |
          ./gradlew clean

      - id: gradlew_assemble
        name: Gradle Assemble
        shell: bash
        run: |
          ./gradlew assemble

      - id: gradlew_jar
        name: Gradle Jar
        shell: bash
        continue-on-error: true
        run: |
          ./gradlew bootJar

      - id: gradlew_test
        name: Gradle Test
        shell: bash
        run: |
          ./gradlew test
        
      

